import { TL_COLORS, TL_FONT } from "../src/tokens.js";

const GENERATED_BANNER = `/*\n * This file is generated by scripts/generate.js.\n * Do not edit directly.\n */\n`;

const FONT_ASSET_DIR = "./assets/fonts/ginora_sans";

export function renderTokensCss() {
  return (
    GENERATED_BANNER +
    `@font-face {\n` +
    `  font-family: "Ginóra Sans";\n` +
    `  src: url("${FONT_ASSET_DIR}/Ginóra-Sans-Regular.otf") format("opentype");\n` +
    `  font-weight: 400;\n` +
    `  font-style: normal;\n` +
    `  font-display: swap;\n` +
    `}\n\n` +
    `@font-face {\n` +
    `  font-family: "Ginóra Sans";\n` +
    `  src: url("${FONT_ASSET_DIR}/Ginóra-Sans-Bold.otf") format("opentype");\n` +
    `  font-weight: 700;\n` +
    `  font-style: normal;\n` +
    `  font-display: swap;\n` +
    `}\n\n` +
    `:root {\n` +
    // Existing, backwards-compatible variables
    `  --tl-blue-dark: ${TL_COLORS.blue.dark};\n` +
    `  --tl-blue-medium: ${TL_COLORS.blue.medium};\n` +
    `  --tl-blue-light: ${TL_COLORS.blue.light};\n` +
    `  --tl-link: ${TL_COLORS.text.link};\n` +
    `  --tl-bg: ${TL_COLORS.background.default};\n` +
    `  --tl-fg: ${TL_COLORS.text.foreground};\n` +
    `  --tl-muted: ${TL_COLORS.text.muted};\n` +
    `  --tl-muted-strong: ${TL_COLORS.text.mutedStrong};\n` +
    `  --tl-green-cta: ${TL_COLORS.green.main};\n` +
    `  --tl-cyan: ${TL_COLORS.accent.cyan};\n` +
    `  --tl-border: ${TL_COLORS.border.strong};\n` +
    `  --tl-blue-overlay: ${TL_COLORS.overlay.blue};\n` +
    `  --tl-modal: ${TL_COLORS.modal};\n` +
    `  --tl-sidebar: ${TL_COLORS.sidebar};\n` +
    `  --tl-font: ${TL_FONT};\n\n` +
    // New vars (additive)
    `  --tl-green-light: ${TL_COLORS.green.light};\n` +
    `  --tl-green-dark: ${TL_COLORS.green.dark};\n` +
    `  --tl-bg-paper: ${TL_COLORS.background.paper};\n` +
    `  --tl-bg-elevated: ${TL_COLORS.background.elevated};\n` +
    `  --tl-text-primary: ${TL_COLORS.text.primary};\n` +
    `  --tl-text-secondary: ${TL_COLORS.text.secondary};\n` +
    `  --tl-text-subtle: ${TL_COLORS.text.subtle};\n` +
    `  --tl-border-default: ${TL_COLORS.border.default};\n` +
    `  --tl-border-subtle: ${TL_COLORS.border.subtle};\n` +
    `  --tl-success: ${TL_COLORS.status.success};\n` +
    `  --tl-warning: ${TL_COLORS.status.warning};\n` +
    `  --tl-danger: ${TL_COLORS.status.danger};\n\n` +
    // Gradients (keep names stable)
    `  --tl-gradient-blue-primary: linear-gradient(135deg, var(--tl-blue-dark) 20%, var(--tl-blue-medium) 80%);\n` +
    `  --tl-gradient-blue-hover: linear-gradient(90deg, var(--tl-blue-medium) 0%, var(--tl-blue-dark) 100%);\n` +
    `  --tl-gradient-text: linear-gradient(to right, var(--tl-blue-medium), var(--tl-blue-light));\n` +
    `  --tl-gradient-hero: linear-gradient(90deg, var(--tl-blue-dark) 0%, var(--tl-blue-light) 100%);\n` +
    `  --tl-gradient-green-cta: linear-gradient(90deg, var(--tl-green-light) 0%, var(--tl-green-cta) 50%, var(--tl-green-light) 100%);\n\n` +
    // shadcn-style base vars (used by some consuming apps)
    `  --background: var(--tl-bg);\n` +
    `  --foreground: var(--tl-fg);\n` +
    `}\n`
  );
}

export function renderTailwindJs() {
  return (
    GENERATED_BANNER +
    `export const tailwindTheme = {\n` +
    `  fontFamily: {\n` +
    `    tl: ['"Ginóra Sans"', 'Arial', 'sans-serif'],\n` +
    `    inter: ['"Ginóra Sans"', 'Arial', 'sans-serif'],\n` +
    `  },\n` +
    `  textColor: {\n` +
    `    "custom-color": "var(--tl-blue-dark)",\n` +
    `  },\n` +
    `  colors: {\n` +
    `    background: "var(--background)",\n` +
    `    foreground: "var(--foreground)",\n` +
    `    "tl-blue": {\n` +
    `      dark: "var(--tl-blue-dark)",\n` +
    `      medium: "var(--tl-blue-medium)",\n` +
    `      light: "var(--tl-blue-light)",\n` +
    `    },\n` +
    `    "tl-blue-dark": "var(--tl-blue-dark)",\n` +
    `    "tl-blue-medium": "var(--tl-blue-medium)",\n` +
    `    "tl-blue-light": "var(--tl-blue-light)",\n` +
    `    "tl-link": "var(--tl-link)",\n` +
    `    "tl-muted": "var(--tl-muted)",\n` +
    `    "tl-muted-strong": "var(--tl-muted-strong)",\n` +
    `    "tl-bg": "var(--tl-bg)",\n` +
    `    "tl-fg": "var(--tl-fg)",\n` +
    `    "tl-green-cta": "var(--tl-green-cta)",\n` +
    `    "tl-success": "var(--tl-success)",\n` +
    `    "tl-warning": "var(--tl-warning)",\n` +
    `    "tl-danger": "var(--tl-danger)",\n` +
    `    "custom-cyan": "var(--tl-cyan)",\n` +
    `    "custom-border": "var(--tl-border)",\n` +
    `    "custom-blue": "var(--tl-blue-overlay)",\n` +
    `    "modal-blue": "var(--tl-modal)",\n` +
    `    sidebar: "var(--tl-sidebar)",\n` +
    `    "light-blue": "var(--tl-blue-medium)",\n` +
    `    "shinning-blue": "var(--tl-blue-light)",\n` +
    `  },\n` +
    `  backgroundImage: {\n` +
    `    "gradient-text": "linear-gradient(to right, var(--tl-blue-medium), var(--tl-blue-light))",\n` +
    `    "custom-gradient": "linear-gradient(90deg, var(--tl-blue-dark) 0%, var(--tl-blue-light) 100%)",\n` +
    `    "gradient-green-cta": "linear-gradient(90deg, var(--tl-green-light) 0%, var(--tl-green-cta) 50%, var(--tl-green-light) 100%)",\n` +
    `  },\n` +
    `};\n`
  );
}

export function renderIndexJs() {
  const colorsJson = JSON.stringify(TL_COLORS, null, 2);

  return (
    GENERATED_BANNER +
    `export const TL_FONT = ${JSON.stringify(TL_FONT)};\n\n` +
    `export const TL_COLORS = ${colorsJson};\n\n` +
    `export const TL_GRADIENTS = {\n` +
    `  bluePrimary: \`linear-gradient(135deg, \${TL_COLORS.blue.dark} 20%, \${TL_COLORS.blue.medium} 80%)\`,\n` +
    `  blueHover: \`linear-gradient(90deg, \${TL_COLORS.blue.medium} 0%, \${TL_COLORS.blue.dark} 100%)\`,\n` +
    `  greenCta: \`linear-gradient(90deg, \${TL_COLORS.green.light} 0%, \${TL_COLORS.green.main} 50%, \${TL_COLORS.green.light} 100%)\`,\n` +
    `};\n\n` +
    `export const TL_TOKENS = {\n` +
    `  font: TL_FONT,\n` +
    `  colors: TL_COLORS,\n` +
    `  gradients: TL_GRADIENTS,\n` +
    `};\n`
  );
}

